//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4971.
// 
#pragma warning disable 1591

namespace fidTailerP.com.fidestin.core {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendHotelEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestCustomerPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestCustomerActivationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback StoresListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalesFiguresOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTwitterOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisplayUnsafeQueryStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckLogonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetDemoDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoreNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCustomerActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCustomerVouchersOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RedeemCustVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogInCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback FBTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RedeemVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerStorePointsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomersPointsDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::fidTailerP.Properties.Settings.Default.fidTailerP_com_fidestin_core_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendHotelEmailCompletedEventHandler SendHotelEmailCompleted;
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event RequestCustomerPasswordCompletedEventHandler RequestCustomerPasswordCompleted;
        
        /// <remarks/>
        public event RequestCustomerActivationCompletedEventHandler RequestCustomerActivationCompleted;
        
        /// <remarks/>
        public event CreateCustomerCompletedEventHandler CreateCustomerCompleted;
        
        /// <remarks/>
        public event IsAliveCompletedEventHandler IsAliveCompleted;
        
        /// <remarks/>
        public event ActivateCustomerCompletedEventHandler ActivateCustomerCompleted;
        
        /// <remarks/>
        public event StoresListCompletedEventHandler StoresListCompleted;
        
        /// <remarks/>
        public event SalesFiguresCompletedEventHandler SalesFiguresCompleted;
        
        /// <remarks/>
        public event UpdateTwitterCompletedEventHandler UpdateTwitterCompleted;
        
        /// <remarks/>
        public event CustomerAccountsCompletedEventHandler CustomerAccountsCompleted;
        
        /// <remarks/>
        public event DisplayUnsafeQueryStringCompletedEventHandler DisplayUnsafeQueryStringCompleted;
        
        /// <remarks/>
        public event CheckLogonCompletedEventHandler CheckLogonCompleted;
        
        /// <remarks/>
        public event ResetDemoDataCompletedEventHandler ResetDemoDataCompleted;
        
        /// <remarks/>
        public event GetStoreNameCompletedEventHandler GetStoreNameCompleted;
        
        /// <remarks/>
        public event IsCustomerActiveCompletedEventHandler IsCustomerActiveCompleted;
        
        /// <remarks/>
        public event ListCustomerVouchersCompletedEventHandler ListCustomerVouchersCompleted;
        
        /// <remarks/>
        public event CreateTransactionCompletedEventHandler CreateTransactionCompleted;
        
        /// <remarks/>
        public event RedeemCustVoucherCompletedEventHandler RedeemCustVoucherCompleted;
        
        /// <remarks/>
        public event LogInCustomerCompletedEventHandler LogInCustomerCompleted;
        
        /// <remarks/>
        public event FBTransactionCompletedEventHandler FBTransactionCompleted;
        
        /// <remarks/>
        public event RedeemVoucherCompletedEventHandler RedeemVoucherCompleted;
        
        /// <remarks/>
        public event CustomerStorePointsCompletedEventHandler CustomerStorePointsCompleted;
        
        /// <remarks/>
        public event GetListCustomersCompletedEventHandler GetListCustomersCompleted;
        
        /// <remarks/>
        public event CustomersPointsDetailCompletedEventHandler CustomersPointsDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendHotelEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendHotelEmail(string To, string Body, string subject) {
            this.Invoke("SendHotelEmail", new object[] {
                        To,
                        Body,
                        subject});
        }
        
        /// <remarks/>
        public void SendHotelEmailAsync(string To, string Body, string subject) {
            this.SendHotelEmailAsync(To, Body, subject, null);
        }
        
        /// <remarks/>
        public void SendHotelEmailAsync(string To, string Body, string subject, object userState) {
            if ((this.SendHotelEmailOperationCompleted == null)) {
                this.SendHotelEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendHotelEmailOperationCompleted);
            }
            this.InvokeAsync("SendHotelEmail", new object[] {
                        To,
                        Body,
                        subject}, this.SendHotelEmailOperationCompleted, userState);
        }
        
        private void OnSendHotelEmailOperationCompleted(object arg) {
            if ((this.SendHotelEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendHotelEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnStatus SendEmail(string To, string From, string Subject, string Body) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        To,
                        From,
                        Subject,
                        Body});
            return ((ReturnStatus)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(string To, string From, string Subject, string Body) {
            this.SendEmailAsync(To, From, Subject, Body, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string To, string From, string Subject, string Body, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        To,
                        From,
                        Subject,
                        Body}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestCustomerPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RequestCustomerPassword(string customeremail) {
            this.Invoke("RequestCustomerPassword", new object[] {
                        customeremail});
        }
        
        /// <remarks/>
        public void RequestCustomerPasswordAsync(string customeremail) {
            this.RequestCustomerPasswordAsync(customeremail, null);
        }
        
        /// <remarks/>
        public void RequestCustomerPasswordAsync(string customeremail, object userState) {
            if ((this.RequestCustomerPasswordOperationCompleted == null)) {
                this.RequestCustomerPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestCustomerPasswordOperationCompleted);
            }
            this.InvokeAsync("RequestCustomerPassword", new object[] {
                        customeremail}, this.RequestCustomerPasswordOperationCompleted, userState);
        }
        
        private void OnRequestCustomerPasswordOperationCompleted(object arg) {
            if ((this.RequestCustomerPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestCustomerPasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestCustomerActivation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RequestCustomerActivation(string email) {
            this.Invoke("RequestCustomerActivation", new object[] {
                        email});
        }
        
        /// <remarks/>
        public void RequestCustomerActivationAsync(string email) {
            this.RequestCustomerActivationAsync(email, null);
        }
        
        /// <remarks/>
        public void RequestCustomerActivationAsync(string email, object userState) {
            if ((this.RequestCustomerActivationOperationCompleted == null)) {
                this.RequestCustomerActivationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestCustomerActivationOperationCompleted);
            }
            this.InvokeAsync("RequestCustomerActivation", new object[] {
                        email}, this.RequestCustomerActivationOperationCompleted, userState);
        }
        
        private void OnRequestCustomerActivationOperationCompleted(object arg) {
            if ((this.RequestCustomerActivationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestCustomerActivationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateCustomer(string Firstname, string LastName, string EMail, string password) {
            object[] results = this.Invoke("CreateCustomer", new object[] {
                        Firstname,
                        LastName,
                        EMail,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCustomerAsync(string Firstname, string LastName, string EMail, string password) {
            this.CreateCustomerAsync(Firstname, LastName, EMail, password, null);
        }
        
        /// <remarks/>
        public void CreateCustomerAsync(string Firstname, string LastName, string EMail, string password, object userState) {
            if ((this.CreateCustomerOperationCompleted == null)) {
                this.CreateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCustomerOperationCompleted);
            }
            this.InvokeAsync("CreateCustomer", new object[] {
                        Firstname,
                        LastName,
                        EMail,
                        password}, this.CreateCustomerOperationCompleted, userState);
        }
        
        private void OnCreateCustomerOperationCompleted(object arg) {
            if ((this.CreateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCustomerCompleted(this, new CreateCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsAlive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] IsAlive() {
            object[] results = this.Invoke("IsAlive", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void IsAliveAsync() {
            this.IsAliveAsync(null);
        }
        
        /// <remarks/>
        public void IsAliveAsync(object userState) {
            if ((this.IsAliveOperationCompleted == null)) {
                this.IsAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAliveOperationCompleted);
            }
            this.InvokeAsync("IsAlive", new object[0], this.IsAliveOperationCompleted, userState);
        }
        
        private void OnIsAliveOperationCompleted(object arg) {
            if ((this.IsAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAliveCompleted(this, new IsAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivateCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActivateCustomer(string EMail) {
            object[] results = this.Invoke("ActivateCustomer", new object[] {
                        EMail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateCustomerAsync(string EMail) {
            this.ActivateCustomerAsync(EMail, null);
        }
        
        /// <remarks/>
        public void ActivateCustomerAsync(string EMail, object userState) {
            if ((this.ActivateCustomerOperationCompleted == null)) {
                this.ActivateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateCustomerOperationCompleted);
            }
            this.InvokeAsync("ActivateCustomer", new object[] {
                        EMail}, this.ActivateCustomerOperationCompleted, userState);
        }
        
        private void OnActivateCustomerOperationCompleted(object arg) {
            if ((this.ActivateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateCustomerCompleted(this, new ActivateCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoresList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Store[] StoresList(int userID, int storeID) {
            object[] results = this.Invoke("StoresList", new object[] {
                        userID,
                        storeID});
            return ((Store[])(results[0]));
        }
        
        /// <remarks/>
        public void StoresListAsync(int userID, int storeID) {
            this.StoresListAsync(userID, storeID, null);
        }
        
        /// <remarks/>
        public void StoresListAsync(int userID, int storeID, object userState) {
            if ((this.StoresListOperationCompleted == null)) {
                this.StoresListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoresListOperationCompleted);
            }
            this.InvokeAsync("StoresList", new object[] {
                        userID,
                        storeID}, this.StoresListOperationCompleted, userState);
        }
        
        private void OnStoresListOperationCompleted(object arg) {
            if ((this.StoresListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoresListCompleted(this, new StoresListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SalesFigures", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalesReport[] SalesFigures(int monthreport, int yearreport, int storeID) {
            object[] results = this.Invoke("SalesFigures", new object[] {
                        monthreport,
                        yearreport,
                        storeID});
            return ((SalesReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SalesFiguresAsync(int monthreport, int yearreport, int storeID) {
            this.SalesFiguresAsync(monthreport, yearreport, storeID, null);
        }
        
        /// <remarks/>
        public void SalesFiguresAsync(int monthreport, int yearreport, int storeID, object userState) {
            if ((this.SalesFiguresOperationCompleted == null)) {
                this.SalesFiguresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalesFiguresOperationCompleted);
            }
            this.InvokeAsync("SalesFigures", new object[] {
                        monthreport,
                        yearreport,
                        storeID}, this.SalesFiguresOperationCompleted, userState);
        }
        
        private void OnSalesFiguresOperationCompleted(object arg) {
            if ((this.SalesFiguresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalesFiguresCompleted(this, new SalesFiguresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTwitter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateTwitter(int transID, long sourceID, string comment) {
            object[] results = this.Invoke("UpdateTwitter", new object[] {
                        transID,
                        sourceID,
                        comment});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTwitterAsync(int transID, long sourceID, string comment) {
            this.UpdateTwitterAsync(transID, sourceID, comment, null);
        }
        
        /// <remarks/>
        public void UpdateTwitterAsync(int transID, long sourceID, string comment, object userState) {
            if ((this.UpdateTwitterOperationCompleted == null)) {
                this.UpdateTwitterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTwitterOperationCompleted);
            }
            this.InvokeAsync("UpdateTwitter", new object[] {
                        transID,
                        sourceID,
                        comment}, this.UpdateTwitterOperationCompleted, userState);
        }
        
        private void OnUpdateTwitterOperationCompleted(object arg) {
            if ((this.UpdateTwitterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTwitterCompleted(this, new UpdateTwitterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerAccounts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerTransaction[] CustomerAccounts(int customerID, string storeID) {
            object[] results = this.Invoke("CustomerAccounts", new object[] {
                        customerID,
                        storeID});
            return ((CustomerTransaction[])(results[0]));
        }
        
        /// <remarks/>
        public void CustomerAccountsAsync(int customerID, string storeID) {
            this.CustomerAccountsAsync(customerID, storeID, null);
        }
        
        /// <remarks/>
        public void CustomerAccountsAsync(int customerID, string storeID, object userState) {
            if ((this.CustomerAccountsOperationCompleted == null)) {
                this.CustomerAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerAccountsOperationCompleted);
            }
            this.InvokeAsync("CustomerAccounts", new object[] {
                        customerID,
                        storeID}, this.CustomerAccountsOperationCompleted, userState);
        }
        
        private void OnCustomerAccountsOperationCompleted(object arg) {
            if ((this.CustomerAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerAccountsCompleted(this, new CustomerAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisplayUnsafeQueryString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DisplayUnsafeQueryString(string safeQueryString) {
            object[] results = this.Invoke("DisplayUnsafeQueryString", new object[] {
                        safeQueryString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DisplayUnsafeQueryStringAsync(string safeQueryString) {
            this.DisplayUnsafeQueryStringAsync(safeQueryString, null);
        }
        
        /// <remarks/>
        public void DisplayUnsafeQueryStringAsync(string safeQueryString, object userState) {
            if ((this.DisplayUnsafeQueryStringOperationCompleted == null)) {
                this.DisplayUnsafeQueryStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayUnsafeQueryStringOperationCompleted);
            }
            this.InvokeAsync("DisplayUnsafeQueryString", new object[] {
                        safeQueryString}, this.DisplayUnsafeQueryStringOperationCompleted, userState);
        }
        
        private void OnDisplayUnsafeQueryStringOperationCompleted(object arg) {
            if ((this.DisplayUnsafeQueryStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayUnsafeQueryStringCompleted(this, new DisplayUnsafeQueryStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckLogon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CheckLogon(string email, string password) {
            object[] results = this.Invoke("CheckLogon", new object[] {
                        email,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLogonAsync(string email, string password) {
            this.CheckLogonAsync(email, password, null);
        }
        
        /// <remarks/>
        public void CheckLogonAsync(string email, string password, object userState) {
            if ((this.CheckLogonOperationCompleted == null)) {
                this.CheckLogonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLogonOperationCompleted);
            }
            this.InvokeAsync("CheckLogon", new object[] {
                        email,
                        password}, this.CheckLogonOperationCompleted, userState);
        }
        
        private void OnCheckLogonOperationCompleted(object arg) {
            if ((this.CheckLogonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLogonCompleted(this, new CheckLogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetDemoData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ResetDemoData(int customerID) {
            this.Invoke("ResetDemoData", new object[] {
                        customerID});
        }
        
        /// <remarks/>
        public void ResetDemoDataAsync(int customerID) {
            this.ResetDemoDataAsync(customerID, null);
        }
        
        /// <remarks/>
        public void ResetDemoDataAsync(int customerID, object userState) {
            if ((this.ResetDemoDataOperationCompleted == null)) {
                this.ResetDemoDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetDemoDataOperationCompleted);
            }
            this.InvokeAsync("ResetDemoData", new object[] {
                        customerID}, this.ResetDemoDataOperationCompleted, userState);
        }
        
        private void OnResetDemoDataOperationCompleted(object arg) {
            if ((this.ResetDemoDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetDemoDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoreName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStoreName(string querystringWithStorecode) {
            object[] results = this.Invoke("GetStoreName", new object[] {
                        querystringWithStorecode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoreNameAsync(string querystringWithStorecode) {
            this.GetStoreNameAsync(querystringWithStorecode, null);
        }
        
        /// <remarks/>
        public void GetStoreNameAsync(string querystringWithStorecode, object userState) {
            if ((this.GetStoreNameOperationCompleted == null)) {
                this.GetStoreNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreNameOperationCompleted);
            }
            this.InvokeAsync("GetStoreName", new object[] {
                        querystringWithStorecode}, this.GetStoreNameOperationCompleted, userState);
        }
        
        private void OnGetStoreNameOperationCompleted(object arg) {
            if ((this.GetStoreNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreNameCompleted(this, new GetStoreNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsCustomerActive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] IsCustomerActive(string email) {
            object[] results = this.Invoke("IsCustomerActive", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void IsCustomerActiveAsync(string email) {
            this.IsCustomerActiveAsync(email, null);
        }
        
        /// <remarks/>
        public void IsCustomerActiveAsync(string email, object userState) {
            if ((this.IsCustomerActiveOperationCompleted == null)) {
                this.IsCustomerActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCustomerActiveOperationCompleted);
            }
            this.InvokeAsync("IsCustomerActive", new object[] {
                        email}, this.IsCustomerActiveOperationCompleted, userState);
        }
        
        private void OnIsCustomerActiveOperationCompleted(object arg) {
            if ((this.IsCustomerActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCustomerActiveCompleted(this, new IsCustomerActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListCustomerVouchers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Voucher[] ListCustomerVouchers(string customercode, int redeemedstatus, string storeID) {
            object[] results = this.Invoke("ListCustomerVouchers", new object[] {
                        customercode,
                        redeemedstatus,
                        storeID});
            return ((Voucher[])(results[0]));
        }
        
        /// <remarks/>
        public void ListCustomerVouchersAsync(string customercode, int redeemedstatus, string storeID) {
            this.ListCustomerVouchersAsync(customercode, redeemedstatus, storeID, null);
        }
        
        /// <remarks/>
        public void ListCustomerVouchersAsync(string customercode, int redeemedstatus, string storeID, object userState) {
            if ((this.ListCustomerVouchersOperationCompleted == null)) {
                this.ListCustomerVouchersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCustomerVouchersOperationCompleted);
            }
            this.InvokeAsync("ListCustomerVouchers", new object[] {
                        customercode,
                        redeemedstatus,
                        storeID}, this.ListCustomerVouchersOperationCompleted, userState);
        }
        
        private void OnListCustomerVouchersOperationCompleted(object arg) {
            if ((this.ListCustomerVouchersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCustomerVouchersCompleted(this, new ListCustomerVouchersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CreateTransaction(string customercode, string customercomment, string queryStringSTAParams) {
            object[] results = this.Invoke("CreateTransaction", new object[] {
                        customercode,
                        customercomment,
                        queryStringSTAParams});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateTransactionAsync(string customercode, string customercomment, string queryStringSTAParams) {
            this.CreateTransactionAsync(customercode, customercomment, queryStringSTAParams, null);
        }
        
        /// <remarks/>
        public void CreateTransactionAsync(string customercode, string customercomment, string queryStringSTAParams, object userState) {
            if ((this.CreateTransactionOperationCompleted == null)) {
                this.CreateTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTransactionOperationCompleted);
            }
            this.InvokeAsync("CreateTransaction", new object[] {
                        customercode,
                        customercomment,
                        queryStringSTAParams}, this.CreateTransactionOperationCompleted, userState);
        }
        
        private void OnCreateTransactionOperationCompleted(object arg) {
            if ((this.CreateTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTransactionCompleted(this, new CreateTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RedeemCustVoucher", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RedeemedVoucher RedeemCustVoucher(string inpRead) {
            object[] results = this.Invoke("RedeemCustVoucher", new object[] {
                        inpRead});
            return ((RedeemedVoucher)(results[0]));
        }
        
        /// <remarks/>
        public void RedeemCustVoucherAsync(string inpRead) {
            this.RedeemCustVoucherAsync(inpRead, null);
        }
        
        /// <remarks/>
        public void RedeemCustVoucherAsync(string inpRead, object userState) {
            if ((this.RedeemCustVoucherOperationCompleted == null)) {
                this.RedeemCustVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRedeemCustVoucherOperationCompleted);
            }
            this.InvokeAsync("RedeemCustVoucher", new object[] {
                        inpRead}, this.RedeemCustVoucherOperationCompleted, userState);
        }
        
        private void OnRedeemCustVoucherOperationCompleted(object arg) {
            if ((this.RedeemCustVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RedeemCustVoucherCompleted(this, new RedeemCustVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogInCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer LogInCustomer(string email, string password) {
            object[] results = this.Invoke("LogInCustomer", new object[] {
                        email,
                        password});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void LogInCustomerAsync(string email, string password) {
            this.LogInCustomerAsync(email, password, null);
        }
        
        /// <remarks/>
        public void LogInCustomerAsync(string email, string password, object userState) {
            if ((this.LogInCustomerOperationCompleted == null)) {
                this.LogInCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogInCustomerOperationCompleted);
            }
            this.InvokeAsync("LogInCustomer", new object[] {
                        email,
                        password}, this.LogInCustomerOperationCompleted, userState);
        }
        
        private void OnLogInCustomerOperationCompleted(object arg) {
            if ((this.LogInCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogInCustomerCompleted(this, new LogInCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FBTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] FBTransaction(int lastPurchaseID, string customercomment) {
            object[] results = this.Invoke("FBTransaction", new object[] {
                        lastPurchaseID,
                        customercomment});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void FBTransactionAsync(int lastPurchaseID, string customercomment) {
            this.FBTransactionAsync(lastPurchaseID, customercomment, null);
        }
        
        /// <remarks/>
        public void FBTransactionAsync(int lastPurchaseID, string customercomment, object userState) {
            if ((this.FBTransactionOperationCompleted == null)) {
                this.FBTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFBTransactionOperationCompleted);
            }
            this.InvokeAsync("FBTransaction", new object[] {
                        lastPurchaseID,
                        customercomment}, this.FBTransactionOperationCompleted, userState);
        }
        
        private void OnFBTransactionOperationCompleted(object arg) {
            if ((this.FBTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FBTransactionCompleted(this, new FBTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RedeemVoucher", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RedeemVoucher(int voucherID) {
            object[] results = this.Invoke("RedeemVoucher", new object[] {
                        voucherID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RedeemVoucherAsync(int voucherID) {
            this.RedeemVoucherAsync(voucherID, null);
        }
        
        /// <remarks/>
        public void RedeemVoucherAsync(int voucherID, object userState) {
            if ((this.RedeemVoucherOperationCompleted == null)) {
                this.RedeemVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRedeemVoucherOperationCompleted);
            }
            this.InvokeAsync("RedeemVoucher", new object[] {
                        voucherID}, this.RedeemVoucherOperationCompleted, userState);
        }
        
        private void OnRedeemVoucherOperationCompleted(object arg) {
            if ((this.RedeemVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RedeemVoucherCompleted(this, new RedeemVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerStorePoints", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CustomerStorePoints(int CustomerID, int storeID) {
            object[] results = this.Invoke("CustomerStorePoints", new object[] {
                        CustomerID,
                        storeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerStorePointsAsync(int CustomerID, int storeID) {
            this.CustomerStorePointsAsync(CustomerID, storeID, null);
        }
        
        /// <remarks/>
        public void CustomerStorePointsAsync(int CustomerID, int storeID, object userState) {
            if ((this.CustomerStorePointsOperationCompleted == null)) {
                this.CustomerStorePointsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerStorePointsOperationCompleted);
            }
            this.InvokeAsync("CustomerStorePoints", new object[] {
                        CustomerID,
                        storeID}, this.CustomerStorePointsOperationCompleted, userState);
        }
        
        private void OnCustomerStorePointsOperationCompleted(object arg) {
            if ((this.CustomerStorePointsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerStorePointsCompleted(this, new CustomerStorePointsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListCustomers() {
            object[] results = this.Invoke("GetListCustomers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListCustomersAsync() {
            this.GetListCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetListCustomersAsync(object userState) {
            if ((this.GetListCustomersOperationCompleted == null)) {
                this.GetListCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListCustomersOperationCompleted);
            }
            this.InvokeAsync("GetListCustomers", new object[0], this.GetListCustomersOperationCompleted, userState);
        }
        
        private void OnGetListCustomersOperationCompleted(object arg) {
            if ((this.GetListCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListCustomersCompleted(this, new GetListCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomersPointsDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerPointsInStore[] CustomersPointsDetail(int customerID) {
            object[] results = this.Invoke("CustomersPointsDetail", new object[] {
                        customerID});
            return ((CustomerPointsInStore[])(results[0]));
        }
        
        /// <remarks/>
        public void CustomersPointsDetailAsync(int customerID) {
            this.CustomersPointsDetailAsync(customerID, null);
        }
        
        /// <remarks/>
        public void CustomersPointsDetailAsync(int customerID, object userState) {
            if ((this.CustomersPointsDetailOperationCompleted == null)) {
                this.CustomersPointsDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomersPointsDetailOperationCompleted);
            }
            this.InvokeAsync("CustomersPointsDetail", new object[] {
                        customerID}, this.CustomersPointsDetailOperationCompleted, userState);
        }
        
        private void OnCustomersPointsDetailOperationCompleted(object arg) {
            if ((this.CustomersPointsDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomersPointsDetailCompleted(this, new CustomersPointsDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnStatus {
        
        private string messageField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerPointsInStore {
        
        private int pointsField;
        
        private int storeIDField;
        
        private string storenameField;
        
        private string address1Field;
        
        /// <remarks/>
        public int points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        public int storeID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string storename {
            get {
                return this.storenameField;
            }
            set {
                this.storenameField = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private string idField;
        
        private string barcodeField;
        
        private string firstNameField;
        
        private string lastField;
        
        private string eMailField;
        
        private bool activeField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RedeemedVoucher))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Voucher {
        
        private int idField;
        
        private int customerIDField;
        
        private int storeIDField;
        
        private string datecreatedField;
        
        private string dateredeemedField;
        
        private string expiresField;
        
        private int valueField;
        
        private string descriptionField;
        
        private string storenameField;
        
        private string townField;
        
        private string customernameField;
        
        private string customeremailField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public int storeID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string datecreated {
            get {
                return this.datecreatedField;
            }
            set {
                this.datecreatedField = value;
            }
        }
        
        /// <remarks/>
        public string dateredeemed {
            get {
                return this.dateredeemedField;
            }
            set {
                this.dateredeemedField = value;
            }
        }
        
        /// <remarks/>
        public string expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
            }
        }
        
        /// <remarks/>
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string storename {
            get {
                return this.storenameField;
            }
            set {
                this.storenameField = value;
            }
        }
        
        /// <remarks/>
        public string town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string customername {
            get {
                return this.customernameField;
            }
            set {
                this.customernameField = value;
            }
        }
        
        /// <remarks/>
        public string customeremail {
            get {
                return this.customeremailField;
            }
            set {
                this.customeremailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RedeemedVoucher : Voucher {
        
        private int successField;
        
        /// <remarks/>
        public int success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerTransaction {
        
        private int idField;
        
        private string purchaseDateField;
        
        private string storenameField;
        
        private int showSafeCustomerIDField;
        
        private string customernameField;
        
        private int customerIDField;
        
        private string purchaseamountField;
        
        private string fBCommentField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string purchaseDate {
            get {
                return this.purchaseDateField;
            }
            set {
                this.purchaseDateField = value;
            }
        }
        
        /// <remarks/>
        public string storename {
            get {
                return this.storenameField;
            }
            set {
                this.storenameField = value;
            }
        }
        
        /// <remarks/>
        public int showSafeCustomerID {
            get {
                return this.showSafeCustomerIDField;
            }
            set {
                this.showSafeCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        public string customername {
            get {
                return this.customernameField;
            }
            set {
                this.customernameField = value;
            }
        }
        
        /// <remarks/>
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string purchaseamount {
            get {
                return this.purchaseamountField;
            }
            set {
                this.purchaseamountField = value;
            }
        }
        
        /// <remarks/>
        public string FBComment {
            get {
                return this.fBCommentField;
            }
            set {
                this.fBCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesReport {
        
        private int totalSalesField;
        
        private int monthdateField;
        
        /// <remarks/>
        public int totalSales {
            get {
                return this.totalSalesField;
            }
            set {
                this.totalSalesField = value;
            }
        }
        
        /// <remarks/>
        public int monthdate {
            get {
                return this.monthdateField;
            }
            set {
                this.monthdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Store {
        
        private int idField;
        
        private string nameField;
        
        private string address1Field;
        
        private string townField;
        
        private string latXField;
        
        private string latYField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string latX {
            get {
                return this.latXField;
            }
            set {
                this.latXField = value;
            }
        }
        
        /// <remarks/>
        public string latY {
            get {
                return this.latYField;
            }
            set {
                this.latYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void SendHotelEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RequestCustomerPasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RequestCustomerActivationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateCustomerCompletedEventHandler(object sender, CreateCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void IsAliveCompletedEventHandler(object sender, IsAliveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ActivateCustomerCompletedEventHandler(object sender, ActivateCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void StoresListCompletedEventHandler(object sender, StoresListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StoresListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StoresListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Store[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Store[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void SalesFiguresCompletedEventHandler(object sender, SalesFiguresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SalesFiguresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SalesFiguresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateTwitterCompletedEventHandler(object sender, UpdateTwitterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTwitterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTwitterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CustomerAccountsCompletedEventHandler(object sender, CustomerAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerTransaction[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerTransaction[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DisplayUnsafeQueryStringCompletedEventHandler(object sender, DisplayUnsafeQueryStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayUnsafeQueryStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayUnsafeQueryStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CheckLogonCompletedEventHandler(object sender, CheckLogonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLogonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLogonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ResetDemoDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetStoreNameCompletedEventHandler(object sender, GetStoreNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoreNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void IsCustomerActiveCompletedEventHandler(object sender, IsCustomerActiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCustomerActiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCustomerActiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ListCustomerVouchersCompletedEventHandler(object sender, ListCustomerVouchersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCustomerVouchersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCustomerVouchersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Voucher[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Voucher[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateTransactionCompletedEventHandler(object sender, CreateTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RedeemCustVoucherCompletedEventHandler(object sender, RedeemCustVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RedeemCustVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RedeemCustVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RedeemedVoucher Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RedeemedVoucher)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LogInCustomerCompletedEventHandler(object sender, LogInCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogInCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogInCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FBTransactionCompletedEventHandler(object sender, FBTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FBTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FBTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RedeemVoucherCompletedEventHandler(object sender, RedeemVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RedeemVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RedeemVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CustomerStorePointsCompletedEventHandler(object sender, CustomerStorePointsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerStorePointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerStorePointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetListCustomersCompletedEventHandler(object sender, GetListCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CustomersPointsDetailCompletedEventHandler(object sender, CustomersPointsDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomersPointsDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomersPointsDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerPointsInStore[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerPointsInStore[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591